[theme]
primaryColor        = "#553C9A"
backgroundColor     = "#F7F8FA"
secondaryBackgroundColor = "#EDEEF2"
textColor           = "#1A202C"
font                = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
